console.log("This site was generated by Hugo.");

let mobileButton = document.getElementById("mobileMenuButton");

mobileButton?.addEventListener("click", (e) => {
  let mobileMenuMenu = document.getElementById("mobileMenuMenu");
  mobileMenuMenu?.classList.toggle("open");
});


let foldingButtons=document.querySelectorAll(".foldingText > button");

foldingButtons.forEach(button => {
  button.addEventListener("click", (e) => {
    button.parentElement?.classList.toggle("open");
  });
});
