console.log("This site was generated by Hugo.");

let num: number = 10;

console.log("Number is", num);

let mobileButton = document.getElementById("mobileMenuButton");

mobileButton?.addEventListener("click", (e) => {
  let mobileMenuMenu = document.getElementById("mobileMenuMenu");
  mobileMenuMenu?.classList.toggle("open");
});
