baseURL = 'https://example.org/'
languageCode = 'de-DE'
title = 'Zahlen-Zeit-Zufriedenheit'


IsMultiLingual = true
DefaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[markup]
[markup.highlight]
noClasses = false


[languages]
[languages.de]
contentDir = 'content/de'
disabled = false
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
title = 'Projekt Dokumentation'
weight = 1
[languages.en]
contentDir = 'content/en'
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'Project Documentation'
weight = 2


[[menus.main]]
name = 'Zahlen'
pageRef = '/erlebnisreise/zahlen'

[[menus.main]]
name = 'Zeit'
pageRef = '/erlebnisreise/zeit'

[[menus.main]]
name = 'Zufriedenheit'
pageRef = '/erlebnisreise/zufriedenheit'

[[menus.main]]
name = 'Home'
pageRef = '/'

[[menus.main]]
name = 'Blog'
pageRef = '/blog'

[[menus.main]]
name = 'Kontakt'
pageRef = '/kontakt'
