baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Zahlen-Zeit-Zufriedenheit'

[markup]
  [markup.highlight]
  noClasses = false


[[menus.main]]
name = 'Zahlen'
pageRef = '/erlebnisreise/zahlen'

[[menus.main]]
name = 'Zeit'
pageRef = '/erlebnisreise/zeit'

[[menus.main]]
name = 'Zufriedenheit'
pageRef = '/erlebnisreise/zufriedenheit'

[[menus.main]]
name = 'Home'
pageRef = '/'

[[menus.main]]
name = 'Blog'
pageRef = '/blog'

[[menus.main]]
name = 'Kontakt'
pageRef = '/kontakt'





[[menus.zzz]]
name = 'Zahlen'
pageRef = '/erlebnisreise/zahlen'

[[menus.zzz]]
name = 'Zeit'
pageRef = '/erlebnisreise/zeit'

[[menus.zzz]]
name = 'Zufriedenheit'
pageRef = '/erlebnisreise/zufriedenheit'


